name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Use the Node.js version that matches your project

      - name: Install Dependencies
        run: |
          cd client
          npm install
          cd ../server
          npm install

      - name: Build Client
        run: |
          cd client
          npm run dev

      - name: Start Server
        run: |
          cd server
          npm start
