name: CI/CD Pipeline for MERN Stack App

# Run this workflow on every push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Use self-hosted GitHub Runner (local machine)

    steps:
    # Step 1: Check out the code from the GitHub repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Node.js for client (React)
    - name: Set up Node.js for client
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Use the Node.js version required by your project

    # Step 3: Install client dependencies
    - name: Install client dependencies
      run: npm install
      working-directory: ./client  # This assumes that your client code is in the "client" folder

    # Step 4: Build the client-side React app
    - name: Build client
      run: npm run build
      working-directory: ./client

    # Step 5: Set up Node.js for server (Express/MongoDB)
    - name: Set up Node.js for server
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Use the Node.js version required by your backend

    # Step 6: Install server dependencies
    - name: Install server dependencies
      run: npm install
      working-directory: ./server  # This assumes that your server code is in the "server" folder

    # Step 7: Restart the server using PM2 (Process Manager)
    - name: Restart the server using PM2
      run: |
        pm2 stop mern-server || true  # Stop the server if it's already running
        pm2 start index.js --name "mern-server"  # Restart the server
      working-directory: ./server  # Run PM2 in the server folder
